export const ROLE_PORT = 'ROLE_PORT';
export const ROLE_PERMISSION_MAPPING_PORT = 'ROLE_PERMISSION_MAPPING_PORT';
export const ROLE_MEMBER_MAPPING_PORT = 'ROLE_MEMBER_MAPPING_PORT';
export const PERMISSION_PORT = 'PERMISSION_PORT';
